# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='submitted',
        ),
        migrations.AddField(
            model_name='topics',
            name='submitted_by',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
