# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Topics', '0002_auto_20170606_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_on', models.DateField()),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='topics',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='selectedtopics',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Topics.Topics'),
        ),
    ]
