# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0003_auto_20170606_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='pass_code',
            field=models.CharField(default='Drc1234', max_length=50),
        ),
    ]
