# Generated by Django 2.1.1 on 2018-10-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
