# Generated by Django 2.1.1 on 2018-10-12 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20181011_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='payment_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
