# Generated by Django 2.1.1 on 2018-10-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20181015_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
