# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180425_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='kitchen/'),
        ),
    ]
