# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20180425_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='uname',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_product',
            field=models.IntegerField(default=0),
        ),
    ]
