# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_auto_20180425_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='chechout',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chechout',
            name='Phone_no',
            field=models.CharField(max_length=13),
        ),
    ]
