# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180425_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
            preserve_default=False,
        ),
    ]
