# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
