# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_product',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
