# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20180430_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='chechout',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chechout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
