# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180430_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chechout',
            name='profile',
        ),
        migrations.AlterField(
            model_name='chechout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Profile'),
        ),
    ]
