# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20180501_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chechout',
            old_name='chechout',
            new_name='user_data',
        ),
    ]
