# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20180501_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_product',
            field=models.PositiveIntegerField(),
        ),
    ]
