# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20180501_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_product',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
