# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20180502_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chechout',
            name='user_data',
        ),
    ]
