# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(verbose_name=shop.models.Product),
        ),
    ]
