# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20180510_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
